### ISSUE TITLE
Music?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/summer-2015#1]
Please add your picks of great summer songs!
- http://www.billboard.com/articles/news/513524/summer-songs-1985-present-top-10-tunes-each-summer-listen
- http://www.nme.com/list/the-ultimate-summer-playlist/178575/page/1
- http://www.amazon.co.uk/Greatest-Ever-Summer-Various-Artists/dp/B0015U7ZOS

**Comment by nelsonic** [comment]
@iteles should we revive our Spotify Premium Membership so we have _all_ the Music...?

**Comment by iteles** [comment]
Spotify premium free trial for 60 days, £9.99 a month thereafter, offer ends 5th July.
https://www.spotify.com/uk/premium/
I'm on it.
![screen shot 2015-06-25 at 13 45 07](https://cloud.githubusercontent.com/assets/4185328/8354499/73479ffe-1b40-11e5-8d51-d01599791441.png)

**Comment by nelsonic** [comment]
Cool. :musical_note: :headphones: :notes: #winning

**Comment by iteles** [comment]
I'm still annoyed there are no Beatles on Spotify. **_grumble, grumble**_

**Comment by nelsonic** [comment]
_**Karaoke**_ ...? :smile:

**Comment by iteles** [comment]
Inevitable :see_no_evil:

**Comment by iteles** [comment]
@rjmk @nikhilaravi @tsop14 @minaorangina @beechware @Lukars @beechware @jackpandas We're still looking for your picks of songs to add to the summer playlist (to avoid streaming and also... #summertime!) :blush: :dancer:

FYI, [this](https://www.youtube.com/watch?v=i1Jp-V4jalI) is currently the song of the summer here in Portugal. @msmichellegar, @nofootnotes and @jrans will tell you all about it... :headphones: :wink:
