### ISSUE TITLE
Air Matress for Moar People?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/summer-2015#15]
:sunny: https://www.sportzone.pt/5007675-intex-jr-twin ?

**Comment by iteles** [comment]
I reckon we need 4. Will confirm once we have final confirmation of numbers.

We'll also need to buy bed linen - I'm working on this (we need more for Gerês anyway) so leave it with me.

**Comment by iteles** [comment]
**Geres:**
- 14 of us at any one time plus possibly @alanshaw, @olizilla & other halves. **Max 18 people**
- Bed space available in actual beds:
  - 5 double beds = 8 people
  - 5 singles
- **Require 5 air mattresses** if Oli, Helen, Alan & Lizzy come

**Lisbon:**
- **10 people total**
- Bed space available in actual beds:
  - 1 double bed = 2 people
  - 3 singles
- **Require 5 air mattresses**

Reckon we can just get 5. In Geres there's a comfy sofa backup and in Lisbon we can get an air mattresses at the drop of a hat if something happens to one :+1:

**Comment by iteles** [comment]
3 bought, 2 to go :+1:

**Comment by olizilla** [comment]
@helenloisward defo won't make it due to work. It's looking less likely that I will make this one also :(

**Comment by nelsonic** [comment]
@olizilla  that makes us all #SadPanda ... :sob: 
![sad panda](http://i1209.photobucket.com/albums/cc397/dunc07/sadpanda.jpg)

But... if this year goes well, will you **_Lead**_ a workshop/day/team **_next year**_...?

**Comment by iteles** [comment]
Also, @heron2014 can't join us any more so we need **4 air mattresses**. 

Already bought :+1:
