### ISSUE TITLE
Add information people need to prepare for journey

### ISSUE THREAD

**Issue by iteles** [dwyl/summer-2015#16]
- [x] Span of time that accommodation is available
- [x] Airport transfers
- [x] Food purchasing arrangements/locations
- [x] Activities and the surrounding area (weekends and afternoons off)
- [x] Recommended clothing 

**General:**
- [x] Sun Screen/Cream (buy/bring/wear) at all times to avoid nasty burns!
- [x] Cash (_Euros_) **[partly covered in useful-info.md, needs updating]**
- [x] Internet conditions
- [x] Freelance agreements

**Comment by iteles** [comment]
@nelsonic Thanks for adding to the above. I unchecked all checked ones though (first three), none of it is covered yet!

**Comment by nelsonic** [comment]
Sorry, I didn't mean to check them as "done".
Each person needs to have their own checklist... Love you! 😘

**Comment by iteles** [comment]
![july-team-dwyl](https://cloud.githubusercontent.com/assets/4185328/8909647/639f00a8-347a-11e5-866d-44aed4284b64.jpg)
