### ISSUE TITLE
Create gitter chat rooms and add badges to readme

### ISSUE THREAD

**Issue by iteles** [dwyl/summer-2015#17]
Initially create one room for each group so that we can have a group location to prep for the trip.
More communication fun to follow once we start working.

**Comment by iteles** [comment]
https://gitter.im/dwyl/team-lake
https://gitter.im/dwyl/team-city

**Comment by nelsonic** [comment]
hmm... can we change "lake" to "_nature_" ?

**Comment by iteles** [comment]
I haven't figured out how. I've emailed gitter.

**Comment by nelsonic** [comment]
@iteles what is the "general" (_open_) chat room for dwyl?
