### ISSUE TITLE
Circle of Sadness

### ISSUE THREAD

**Issue by nelsonic** [dwyl/summer-2015#20]
Watch: https://www.youtube.com/watch?v=o5c1gIzQoPI _and_ https://youtu.be/FJ5VCoan-VI?t=43s

Anyone who does not feel like this: https://www.youtube.com/watch?v=C_ODFtJckRQ needs **_DWYL**_

Anyone who is not **_excited**_ about this movie: https://www.youtube.com/watch?v=kAgJcEmMTek needs to re-discover their inner-awesome!

**Comment by nelsonic** [comment]
@dwyl/doers _who_ is interested in going to watch [_**Inside Out**_](http://www.imdb.com/title/tt2096673/) this Friday night at the Cinema...?

**Comment by tonydaly** [comment]
@nelsonic where's it showing? Thought it wasn't out till next month. I'm very hesitant to watch it with other people as there's a massive chance I'll start crying like a baby...

**Comment by nelsonic** [comment]
@tonydaly you're right! ... its only coming out July :cry: 
I'm _so excited_ to watch it that I read the release date wrong... sad times.
its going to be the _**Best Movie Ever!!**_

**Comment by iteles** [comment]
BUT there _is_ [The Minions Movie](https://booking.myvue.com/OnlineBooking.aspx?cinemaid=10074&sessionId=153748) at Westfield Vue cinema at 19h35 this Friday (tomorrow). Up for it @tonydaly / @dwyl/doers ?

**Comment by iteles** [comment]
Closing this issue as we've now seen them :blush: :+1:
