### ISSUE TITLE
Take Acoustic Guitar to Portugal?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/summer-2015#23]
Should we take the Acoustic Guitar to Portugal?
@Jasonspd we could pay for the extra hold luggage allowance if you don't mind taking it...
means you get to play us few tunes... :wink: 

@gregaubs thanks for reminding me!

**Comment by nelsonic** [comment]
@izaakrogan I might take you up on the offer... have you already booked hold luggage for your flight?
and _more importantly_ have you convinced Emily to go?

**Comment by izaakrogan** [comment]
I don't have hold luggage but it won't be difficult to add it... Emily has work :disappointed:

**Comment by nelsonic** [comment]
What...?! surely she has _weekends_ ? :disappointed:

**Comment by nelsonic** [comment]
Well, if you don't mind investigating about adding hold luggage, that would be super useful. thanks!

**Comment by izaakrogan** [comment]
She's in Sweden for the whole 2 weeks

**Comment by nelsonic** [comment]
@izaakrogan can you drag in a screenshot of how much it will be to add a hold luggage item to your flight (one-way) ? 

The alternative is getting one there: http://www.fnac.pt/Guitarra-Classica-3-4-Stagg-C530-Instrumento-Musical-Instrumentos-Corda/a332151#bl=HGMERCHPDD5

**Comment by izaakrogan** [comment]
@jrans will you have enough space in your hold luggage? I guess not but let me know

**Comment by iteles** [comment]
Done! Thanks @izaakrogan :+1:
