### ISSUE TITLE
Invite Moar (Awesome) People to July?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/summer-2015#24]
@diasdavid que fazes na segunda semana de Julho...?

**Comment by daviddias** [comment]
Vou estar fora do país até 19 de Agosto. Mas obrigado pelo convite.
Fala com a malta do requireLX - https://gitter.im/require-lx/community

**Comment by nelsonic** [comment]
@diasdavid sad you can't make it, hope life is treating you super well!
Muito obrigado por nos lembrares da requireLX community!
Boas viagens! :airplane: :wink: 
Abraço!

**Comment by iteles** [comment]
Invited requireLX: https://twitter.com/nelsonic/status/614664435358134272

Also invited the lovely @alanshaw, @achingbrain and @olizilla at Meteor London and a few other cool cats :+1: 
Closing the issue.

@nelsonic /everyone, let me know if there's anyone else we haven't invited yet that really should be there!
