### ISSUE TITLE
Freelance agreements

### ISSUE THREAD

**Issue by iteles** [dwyl/summer-2015#27]
Need to put together some freelance agreements for folks coming to work on dwyl this summer, particularly given that we're open sourcing all our code, we don't want there to be any doubt that everyone understands their code will be available to the world!

**Comment by nelsonic** [comment]
These are usually called **Contributor Agreements**... https://www.clahub.com/

Interesting discussion: http://programmers.stackexchange.com/questions/191535/could-submitting-a-pull-request-ever-constitute-accepting-a-contributor-licence

**Comment by iteles** [comment]
The circumstances around this summer are slightly different to people we don't know from across the world contributing things they've built for their own use for example. My plan is to have _summer-specific freelance agreements_ and then _more general contributor agreements_ for dwyl :+1:

**Comment by nelsonic** [comment]
agree.
Anyone else have any insight on this?

**Comment by iteles** [comment]
![so-stoked-brushcript-lettering-neil-secretario](https://cloud.githubusercontent.com/assets/4185328/8432994/4583c620-1f3b-11e5-93d4-ceba0bf3179d.png)

<small>'So Stoked' artwork above by [Neil Secretario](https://www.behance.net/gallery/14266643/Brush-Lettering-Collection-No-1)</small>

**Comment by nelsonic** [comment]
I don't think the Contributor Agreement should be hidden away in the "Summer" repo...

**Comment by iteles** [comment]
@nelsonic TOTALLY agree with you. My plan is:
- Summer repo freelance agreement
- Immediately add a contributor agreement to an agreements repo or maybe the launch repo? (I would prefer a catch-all repo for things like this)
- Talk it over with all of the lovely people working with us this summer
- Update and add to general dwyl repo

(Again, I'm [differentiating between a **freelance** agreement and a **contributor** agreement](https://github.com/dwyl/summer-2015/issues/27#issuecomment-116275483))
