### ISSUE TITLE
Mobile internet

### ISSUE THREAD

**Issue by iteles** [dwyl/summer-2015#28]
Always good to have a little backup internet.

@nelsonic and @iteles will also need it for time outside of the 4 weeks of summer-2015 when spending time in Landim or other internetless locations for example.
- [x] Research available options and prices
- [x] Decide what we actually need to get in terms of GBs
- [ ] Purchase on 02-Jul when we get to PT

**Comment by nelsonic** [comment]
ALL The GBs of DATA! :stuck_out_tongue_winking_eye: 

There are a couple of wifi hotspot style devices we can use with a 4G rolling contract.

This is the one I was thinking: https://loja.vodafone.pt/homephone/pack.htm?pid=1187-10
![vodafone-pt-wifi-hotspot-3g](https://cloud.githubusercontent.com/assets/194400/8397851/f54e9e4c-1dd1-11e5-8b48-f82199fc5d46.png)

Or... you could use your iPone 6 (which has a _really_ good 4G chip and antenna and means we don't have to buy an extra device...) and then use iP5 for ur GiffGaff...

**Comment by iteles** [comment]
**MEO**
- [MEO pens are expensive](https://loja.meo.pt/Equipamentos/Pens/MEO/4G-150-Mb)
- [Payment plans](https://www.meo.pt/internet/internet-movel/tarifarios/pc-tablet) - not great.
- [Sharing internet over more than one device](https://www.meo.pt/internet/internet-movel/cartao-partilhavel)

**NOS**
- [Kanguru 4G hotspot](http://loja-equipamentos.nos.pt/particulares/montra/pens-routers/detalhe/16204/Kanguru%20/Hotspot%20Kanguru%204G%20150Mbps%20) €70
- [Kanguru 4G pen](http://loja-equipamentos.nos.pt/particulares/montra/pens-routers/detalhe/15161/Kanguru%20/Pen%20Kanguru%204G%20100%20L100) €50
- [Prepayment plans](http://www.nos.pt/particulares/internet/internet-movel/tarifarios/Paginas/tarifarios-por-carregamento.aspx) = **€25 for 2GB over a 90 day period** + €12.50 per GB after that + [€9.90 for the card](http://loja-equipamentos.nos.pt/particulares/montra/cartoes/detalhe/15165/Kanguru%20/Carto%20Kanguru%20Universal%20Nano%20SIM)
  ![NOS-mobile-internet-coverage](https://cloud.githubusercontent.com/assets/4185328/8397904/88ba4d88-1dd3-11e5-995e-84155e58200f.png)

**Vodafone**
- [Pens and Hotspots](http://www.vodafone.pt/main/particulares/internet-movel/pens-hotspots.html) - €35 to €70
- [Payment plans](http://www.vodafone.pt/main/particulares/internet-movel/tarifarios/go-detalhe.html) = **€25 for 2GB over a 60 day period** + €10 per GB after that + [€12.50 for the card](https://loja.vodafone.pt/cartoes-sim/cartao-dados.html)

**GiffGaff**
Using my iPhone as a hotspot, 19p per MB on roaming

**LycaMobile**
(more expensive)

**Lisbon Unlimited** (thanks @nelsonic :+1: )
Based at LX airport:
![mobile-internet-lx-airport](https://cloud.githubusercontent.com/assets/4185328/8397903/7f7c3484-1dd3-11e5-830a-3be095c5a4e9.jpg)

**Comment by nelsonic** [comment]
https://www.facebook.com/Lisbon.Unlimited.4G.WiFi

**Comment by iteles** [comment]
@nelsonic Do you reckon 2GB will be enough? 
If not, the Lisbon airport one is looking pretty good!

**Comment by nelsonic** [comment]
2GB for how long? per week?

**Comment by iteles** [comment]
Ha, no, for the duration! We'll hardly ever be in places without wifi so I figured this might be emergency-only. Realistically though, let's go for the Lisbon airport one, it's safer and then we can re-evaluate after the 30 day period is up. :+1:

**Comment by nelsonic** [comment]
2GB should be "enough" but it means we won't be "always on". That can be a good thing cause we would get more work done if we only go online at specific times.
But I Google a _**LOT**_ while getting work done...

**Comment by iteles** [comment]
The Vodafone and NOS ones don't have time limits, just data limits. 
The only place I really foresee this being used is Landim and as a backup in Geres. Let's go for the LX airport one as a starter.

**Comment by iteles** [comment]
Have been in touch with the LX airport guys and their 'summer pricing' means it's now €50 for 30 days/15GB. It's still cheaper than Vodafone **if we use anything above 4GB**...

**Comment by iteles** [comment]
Went with the 15GB for €50 option. Will revisit on 3-August-2015.
