### ISSUE TITLE
Car Door Magnets?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/summer-2015#3]
Should we order car door magnets to put on which ever vehicle(s) we end up driving this summer?
See: http://www.vistaprint.co.uk/car-door-magnets.aspx

![vistaprint-car-door-magnet-1of2](https://cloud.githubusercontent.com/assets/194400/7850517/5258026e-04db-11e5-8998-7d651b0c37cf.png)
![vistaprint-car-door-magnet-2of2](https://cloud.githubusercontent.com/assets/194400/7850518/5581d08c-04db-11e5-8d66-4e0d84d1ff8e.png)

Related to (but not _dependent_ on): https://github.com/nelsonic/nelsonic.github.io/issues/10

Alternative Suppliers:
- http://www.buildasign.co.uk/magnetic-signs (crappy website. product looks good tho)
- http://www.magnetstreet.com/shop/car-magnets (less customisable design)
- http://www.overnightprints.com/carmagnets (US&A)

**Comment by iteles** [comment]
Linked to https://github.com/dwyl/start-here/issues/17

**Comment by nelsonic** [comment]
Agreed. we can totes use the _Big Stickers_ as MVP and if we want to be able to remove them we can always upgrade to Magnets laters.
