### ISSUE TITLE
Summer Reading - Please Come Upstairs today and Select 1-3 books to read.

### ISSUE THREAD

**Issue by nelsonic** [dwyl/summer-2015#31]
Hi Awesome Peoples!
Please come upstairs and take your pick of up to 3 books for reading this summer.
![image](https://cloud.githubusercontent.com/assets/194400/8457150/a49bc924-2007-11e5-930a-ee770805037a.jpg)

We ask that you 
1. Once you have chosen your 1-3 book(s) please Submit a **Pull Request** to: https://github.com/dwyl/start-here/blob/master/books-to-read.md listing the book(s) you intend to read. 
2. Bring them with you to Portugal (if you are coming)
3. Once you have finished reading it, please update the **books-to-read.md** doc with what you learned.

Thanks!

**Comment by iteles** [comment]
@dwyl/doers There are still a few PRs missing :) Did anyone grab _essentialism_ by the way?
