### ISSUE TITLE
What's our hashtag?

### ISSUE THREAD

**Issue by msmichellegar** [dwyl/summer-2015#32]
# dwylsummer?

**Comment by claireinez** [comment]
The all-important question

**Comment by iteles** [comment]
:heart: Is #dwylsummer2015 too long? Plus #dwyl of course!

**Comment by msmichellegar** [comment]
I feel like #dwylsummer is taking off ;)

**Comment by iteles** [comment]
Totally agree! #dwylsummer & #dwyl it is
