### ISSUE TITLE
Add note on how to sign the agreements

### ISSUE THREAD

**Issue by iteles** [dwyl/summer-2015#35]
I can do screen grabs for Mac but need some help with the windows and linux ones!

**Comment by iteles** [comment]
<img width="439" alt="preview-annotate-menu-for-freelance-agreements" src="https://cloud.githubusercontent.com/assets/4185328/8646836/efca8f24-294a-11e5-8f43-64b1890ff61a.png">

<img width="208" alt="preview-add-text-for-freelance-agreements" src="https://cloud.githubusercontent.com/assets/4185328/8646735/4101a27a-294a-11e5-91f4-377dd53434e4.png">

<img width="378" alt="preview-altered-text-for-freelance-agreements" src="https://cloud.githubusercontent.com/assets/4185328/8646772/7910ec52-294a-11e5-9934-458242aec9af.png">

<img width="182" alt="preview-create-signature-for-freelance-agreements" src="https://cloud.githubusercontent.com/assets/4185328/8646908/7477c4da-294b-11e5-8b97-c8019900cf7d.png">

**Comment by iteles** [comment]
@Jasonspd Could really use your help on the Ubunto stuff! :wink:

**Comment by Jasonspd** [comment]
#Ubuntu
- Use the Ubuntu Software Centre and install "xournal" for annotating PDF files
- Open the PDF with "xournal" and annotate that PDF
- File > Export as PDF > DONE!

![screenshot from 2015-07-13 11 20 08](https://cloud.githubusercontent.com/assets/10106517/8647618/7405bce0-2951-11e5-80e5-58ca8132fefa.png)
![screenshot from 2015-07-13 11 20 33](https://cloud.githubusercontent.com/assets/10106517/8647619/75f3af62-2951-11e5-8a90-bfda435d7949.png)

**Comment by iteles** [comment]
Feel free to PR this @Jasonspd :wink: Thanks!

**Comment by nelsonic** [comment]
@Jasonspd looking good!
all that we ask is that you attempt to focus your screenshots on just the important bits (_use selection tool instead of full-screen screenshots_) 
thanks! :+1:

**Comment by iteles** [comment]
@anniva Did you use this too? Find a better way?
Reckon you could help us out with a quick PR? :blush:

**Comment by anniva** [comment]
@iteles I used Jason's way, which worked well :)

**Comment by iteles** [comment]
![xournal-ubuntu](https://cloud.githubusercontent.com/assets/4185328/9004130/56e276c6-376b-11e5-8116-db0102c44c5d.png)
![xournal-ubuntu-annotate-pdf](https://cloud.githubusercontent.com/assets/4185328/9004750/ab7e5574-3770-11e5-8811-4ed845f40896.png)

**Comment by iteles** [comment]
Thanks @anniva :+1:

**Comment by iteles** [comment]
For Windows: http://www.howtogeek.com/164668/how-to-electronically-sign-documents-without-printing-and-scanning-them/
