### ISSUE TITLE
Can not "firma" (sign the pdf)

### ISSUE THREAD

**Issue by besarthoxhaj** [dwyl/summer-2015#36]
The option "firma" (sign) is gray out in my computer. 

![schermata 2015-07-13 alle 10 55 32](https://cloud.githubusercontent.com/assets/7887496/8647223/f7d6bad2-294d-11e5-90b5-cf0808914ad8.png)

What I'm missing?
# summer2015 #dwyl

**Comment by iteles** [comment]
@besarthoxhaj I've been googling and googling and it looks like this is a relatively unique problem! I [found this](http://forums.macrumors.com/threads/preview-app-question.1468877/) though - could you please check your preferences menu to see if you can activate the signature from there?

I don't have it in my preferences menu but your version of Preview looks different to mine!

Could you please also let me know what OS and version of Preview you're running?

**Comment by iteles** [comment]
@besarthoxhaj We're closing this issue as you we got a signed freelance agreement from you and haven't been able to replicate the issue. We hope anyone else who shares this issue will be able to open it again and we can hopefully find the steps to replicate it and solve it then! :+1:
