### ISSUE TITLE
People still ask how to digitally sign the freelance agreements

### ISSUE THREAD

**Issue by iteles** [dwyl/summer-2015#38]
We create a `how-do-I-sign-this.md` file as part of resolving #35, but at least 50% of people _still ask how to :evergreen_tree: digitally sign :evergreen_tree: the agreement.

<img width="932" alt="how-do-i-sign-this-highlighted-screenshot" src="https://cloud.githubusercontent.com/assets/4185328/8945651/35cfa468-3581-11e5-900e-5417326ae96b.png">

**Proposed solution to be tested with 'team city':** Make the `how-do-I-sign-this.md` file the `readme.md` for this sub-directory so that it appears below the file list as soon as people open the `freelance-agreements` sub-directory.

**Comment by nelsonic** [comment]
Agreed. The hypothesis that `git mv how-do-I-sign-this.md README.md` will answer the question for most people. :+1:
