### ISSUE TITLE
Where do we put photos?

### ISSUE THREAD

**Issue by msmichellegar** [dwyl/summer-2015#39]
Can we/should we create a repo for awesome photos from #dwylsummer? Where are photos living right now?

**Comment by iteles** [comment]
A very good question! I haven't even had a chance to get them off the various devices and onto a harddrive yet but what does everyone reckon @dwyl/doers?

**Comment by nelsonic** [comment]
@msmichellegar I think @iteles had a plan for this. 
At the moment _my_ photos are all on our portable hard drive. 
We were thinking of building a Photo Gallery component for https://github.com/nelsonic/adoro (which will _soon_ get transferred to dwyl) which we would use to showcase our lovely photos ...

**Comment by iteles** [comment]
Mine and DSLR's are still on the respective devices. I'm formulating various plans for this but we may end up needing a short term solution as well as a long term one!

**Comment by msmichellegar** [comment]
Cool!
