### ISSUE TITLE
QuadCopters for aerial photography awesomeness?!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/summer-2015#4]
Should we get a Parrot Bebop Drone or DJI Phantom 3 or **_Both**_? :wink: 

[![Parrot Bebop Drone](http://i.imgur.com/9KB3w7d.png)](https://www.youtube.com/watch?v=WUpmPUcnuBY)

[![Phantom 3](http://i.imgur.com/Ez2roaK.png)](https://www.youtube.com/watch?v=7jJn7uvqgc0)
- Bebop: http://www.amazon.co.uk/Parrot-Bebop-Drone-Skycontroller-Yellow/dp/B00OOR98UI/
- Phantom 3: http://www.amazon.co.uk/DJI-Phantom-Professional-Quadcopter-Batteries/dp/B00W6PP1A6
  Relates to: https://github.com/nelsonic/nelsonic.github.io/issues/11

**Comment by nelsonic** [comment]
Cheaper bebop: http://www.simplyelectronics.net/mainproduct.php?pid=25730 £352.95 (just drone)
Inspirational holiday video: https://www.youtube.com/watch?v=cyInX4reaAc

**Comment by eventhough** [comment]
Phantom fo shoooo! What is this for?

**Comment by olizilla** [comment]
@andrew mentioned that the DJI is pretty awesome.

**Comment by andrew** [comment]
The bebop is hackable and the dji will chop your fingers off, if it's for photography is go with the dji with a go pro

**Comment by nelsonic** [comment]
@eventhough the quads are for people to _fly_ when taking a break from coding.
**Background**: this summer we are running a coding retreat (similar to [nodeconf](https://twitter.com/nodeconf/status/588746940898271232) but smaller and _focussed_ on building actual software products!) but in [Portugal](http://marionstclaire.com/wp-content/uploads/2014/10/peneda-geres-national-park.jpg) ... _everyone's_ invited!!  
We know Portugal might be a bit far for some people (_this time_) but next year we hope to announced it much earlier so people can book tickets in advance and will subsidise flights for cool people we really want to come! :wink:

@andrew thanks for confirming the Bebop is hackable. we'll order two of those. :+1: 
And for the more experienced flyers, we'll have a DJI fully loaded to get insanely awesome photos!

@dwyl/doers if anyone else is _curious_ ask @iteles for the details... Invites going out _soon_!

**Comment by andrew** [comment]
@nelsonic also the rolling spider is hackable and quite a lot smaller/cheaper: http://www.parrot.com/usa/products/rolling-spider/

**Comment by nelsonic** [comment]
@andrew hadn't considered the spider because of the _mixed_ AMZN reviews: http://www.amazon.co.uk/Minidrone-Rolling-Spider-Parrot-Gadget/dp/B00LX0A0PG
but on you're recommendation, we'll order one for variety. What else do we need to have kit-wise to have a great time hacking the parrot? _thanks_!

**Comment by andrew** [comment]
I've not had any trouble with mine and I believe @voodootikigod has been using them for hacking and nodecopter related things.

**Comment by nelsonic** [comment]
Sweet! :candy: 
Found: https://github.com/FluffyJack/node-rolling-spider
#**excited** !!
Thanks @andrew

**Comment by nelsonic** [comment]
How to pilot the Bebop Drone: http://blog.parrot.com/2014/11/18/how-to-pilot-bebop-drone/
(I've ordered one... :stuck_out_tongue_winking_eye: its going to be loco! )

**Comment by nelsonic** [comment]
Parrot Bebop Drone was good. sadly it does not have the built-in stability and collision detection so it did not last v. long ... (_went for a swim when we tried to fly it over a pond_)
Hopefully next time we investigate drones they will be more autonomous ... 
e.g: DJI Phantom 4: https://www.youtube.com/watch?v=JJPSSqMQajA
(_but I don't have budget (time!) for one right now..._)
