### ISSUE TITLE
Who wants profile photos?

### ISSUE THREAD

**Issue by iteles** [dwyl/summer-2015#40]
I know @nelsonic and often mention we want to take some good photos of ourselves we can use as profile pictures. High resolution, interesting backgrounds and well focused, like http://www.foryourself.co/#/jongold or http://www.foryourself.co/#/alexx_rae

Seeing as [Lisbon is kind of stunning](http://www.theportugalnews.com/news/lisbon-voted-worlds-fourth-most-beautiful-city/27894) (a **totally** and _unashamedly_ biased point of view) and we have a pretty sweet [DSLR](https://en.wikipedia.org/wiki/Digital_single-lens_reflex_camera), #dwylsummer might be a good time to get some shots.

<img width="749" alt="lisbon-on-instagram-screenshot-of-photos" src="https://cloud.githubusercontent.com/assets/4185328/8947296/090927be-3591-11e5-9633-9e2c946c1f54.png">
_(from [@Lisboninsta](https://instagram.com/lisboninsta/) on Instagram)_

**Comment by iteles** [comment]
@minaorangina @rjmk @tsop14 @jackpandas @beechware @FilWisher @nikhilaravi @nelsonic What say you? :sunglasses:

**Comment by tsop14** [comment]
Yes please! :camera: :sunny:

**Comment by nikhilaravi** [comment]
:+1:

**Comment by nelsonic** [comment]
@iteles when are we time-tabling this?

**Comment by iteles** [comment]
Either Friday afternoon post segways or Saturday?

**Comment by iteles** [comment]
We ended up not doing this as folks didn't really feel like going into Lisbon Friday or Saturday, but we certainly got some lovely photos. @nelsonic Shall we try and get some for ourselves?

**Comment by nelsonic** [comment]
When ever you are free. :camera:

**Comment by iteles** [comment]
Definitely one to remember for next year! I've added a #dwylsummer2016 milestone. Shall we close it for now and add it as an issue to dwyl-summer2016 in January?

**Comment by nelsonic** [comment]
Agreed. :+1:
