### ISSUE TITLE
New Camera for Parrot Bebop Drone?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/summer-2015#41]
@iteles where do you have as your ebay delivery address?
given that the Bebop drone camera lens is scratched I was thinking of ordering:
- http://www.ebay.co.uk/itm/BRAND-NEW-IN-SEALED-RETAIL-PACK-GENUINE-PARROT-BEBOP-DRONE-HD-FRONT-CAMERA-/231633807637
- http://www.ebay.co.uk/itm/Parrot-Bebop-Drone-3-0-Part-Camera-Transparent-Cover-Case-Dust-Guard-Shield-New-/151711308023

We could then aksk someone from the August Crew to bring it over (_it will be like 200g and take up zero space_)

**Comment by iteles** [comment]
My current eBay address is our house but things can easily be sent to F&C. 

I'll get Andrew to bring our 'spare parts' kit from Lisbon tomorrow and hopefully we won't need to order this :blush:

**Comment by nelsonic** [comment]
Where exactly are you expecting to find this "spare parts" kit...?

**Comment by iteles** [comment]
Oh, I thought it was still in Lisbon but apparently it's here :+1:
