### ISSUE TITLE
Should the 'definition of done' be its own repository?

### ISSUE THREAD

**Issue by iteles** [dwyl/summer-2015#42]
The 'definition of done' is a critical part of working with us and keeping the quality of what we do high. It shouldn't be hidden away in `summer-2015` as this doesn't give it the importance it's due.

I think we should have a `definition-of-done` repo (PR #34) that we can point to from a broader, `how-we-work` repo. Here we would talk about timing your tasks, how we communicate as a team and also point to other repos such as [contributing](https://github.com/dwyl/contributing), our coding style guide #22 and our [code of conduct](https://github.com/dwyl/code-of-conduct).

Should we have the definition of done as the top of this `how-we-work` repo **for now** to keep people from having to click around for information, or should we **break it out into its own repo straight away**?

**Comment by nelsonic** [comment]
Its probably the single most important thing in any project. so yes, its' own repo. please/thanks! :+1:
