### ISSUE TITLE
Cabo da Roca

### ISSUE THREAD

**Issue by tsop14** [dwyl/summer-2015#45]
Shall we? 

@dwyl/summer

**Comment by nelsonic** [comment]
@tsop14 it _really_ depends on people who have to be at the airport at specific time...
Segway will only finish ~ 13:00 
What time do people need to be places?

**Comment by iteles** [comment]
@dwyl/summer What time do people need to be places on Friday?

P.S. Cabo da Roca is a 20 minute drive from the segways and probably 1-1.5 hours from the airport (depending on traffic)

_P.P.S. Love the use of the **enhancement** label_ :wink: :+1:

**Comment by minaorangina** [comment]
I need to be at the airport by half 5

**Comment by iteles** [comment]
I think we managed this and then some!

![img_5034](https://cloud.githubusercontent.com/assets/4185328/9564005/a6d28e24-4e8f-11e5-8095-130790fc8e40.JPG)
![img_5036](https://cloud.githubusercontent.com/assets/4185328/9564016/e718d60a-4e8f-11e5-8c82-9e2745a03e33.JPG)
![img_5039](https://cloud.githubusercontent.com/assets/4185328/9564009/af96f20c-4e8f-11e5-80d4-ac50ebbbb40b.JPG)
![img_5155](https://cloud.githubusercontent.com/assets/4185328/9564011/b0e397fa-4e8f-11e5-8448-af9e01a4937c.JPG)

![img_5105](https://cloud.githubusercontent.com/assets/4185328/9564002/992b008a-4e8f-11e5-828e-cdbe961aa42a.jpg)
![img_5073](https://cloud.githubusercontent.com/assets/4185328/9564003/992b6c64-4e8f-11e5-9313-b2ad531b3699.jpg)
