### ISSUE TITLE
2016

### ISSUE THREAD

**Issue by nelsonic** [dwyl/summer-2015#49]
![summer-code-logo](https://cloud.githubusercontent.com/assets/194400/17839685/7952017e-67e7-11e6-9d86-d66db0e34856.png)

**Comment by iteles** [comment]
This is my second highest priority task for Tuesday (but most likely Monday night).

**Comment by iteles** [comment]
![dwyl-summer-2015-tweet-collage](https://cloud.githubusercontent.com/assets/4185328/17987260/e75860d2-6b16-11e6-9817-134d47007806.jpg)

**Comment by iteles** [comment]
![mosteiro de landim - vista tipica](https://cloud.githubusercontent.com/assets/4185328/17987467/0b91016a-6b18-11e6-84ee-0ffbefdd482b.JPG)

**Comment by nelsonic** [comment]
@mk4111 ...
![marie-lake](https://cloud.githubusercontent.com/assets/194400/23144150/98f50f24-f7bd-11e6-8ae9-df75b3bda72c.jpg)
(_clearing off my camera to make space for more photos..._)

**Comment by nelsonic** [comment]
@jackcarlisle + @Conorc1000 
![jack-connor-sun](https://cloud.githubusercontent.com/assets/194400/23144201/edbb743a-f7bd-11e6-8560-9174b5293eb7.jpg)
![jack-connor-pingpong](https://cloud.githubusercontent.com/assets/194400/23144285/776e58be-f7be-11e6-9c1d-da3e63f839b4.jpg)

**Comment by nelsonic** [comment]
@eliascodes + @shouston3 
![elias-sam-django](https://cloud.githubusercontent.com/assets/194400/23144256/38f001b4-f7be-11e6-9972-8f879424907a.jpg)

**Comment by nelsonic** [comment]
@JMurphyWeb + @mk4111 
![jack-coding-indoors](https://cloud.githubusercontent.com/assets/194400/23144312/a02f0aaa-f7be-11e6-8772-cd0e9947a779.jpg)
![jack-marie-indoors](https://cloud.githubusercontent.com/assets/194400/23144333/c33fc890-f7be-11e6-9505-0728dc46ff47.jpg)
(_we should take cable ties next time..._) 😉

**Comment by nelsonic** [comment]
@jrans 
![ransy-head-scratcher](https://cloud.githubusercontent.com/assets/194400/23144381/0dc5a1a0-f7bf-11e6-9c1b-36f32c9ef1f9.jpg)
![jack-rans-marshmallow](https://cloud.githubusercontent.com/assets/194400/23144408/31629c1c-f7bf-11e6-9c6d-e2226a2b04f8.jpg)

**Comment by nelsonic** [comment]
@SimonLab 
![simon-marshmallow](https://cloud.githubusercontent.com/assets/194400/23144429/6bb5e14e-f7bf-11e6-9047-c0ae66f77c8d.jpg)

**Comment by nelsonic** [comment]
@des-des 🍰 
![happy-birthday-eoin](https://cloud.githubusercontent.com/assets/194400/23144434/7346281a-f7bf-11e6-8795-d53f9dd6299f.jpg)

**Comment by nelsonic** [comment]
@roryc89 + @jackcarlisle 
![rory-jack-bbq](https://cloud.githubusercontent.com/assets/194400/23144472/c61bff42-f7bf-11e6-8273-04735ac05881.jpg)

**Comment by nelsonic** [comment]
@naazy + @harrygfox 
![naaz-leading-the-demo](https://cloud.githubusercontent.com/assets/194400/23144674/297852d8-f7c1-11e6-983a-d7c703fdbe47.jpg)
![naaz-playing-pool](https://cloud.githubusercontent.com/assets/194400/23144676/2b6b9fc8-f7c1-11e6-9a7c-218cd6392e47.jpg)
![game-night](https://cloud.githubusercontent.com/assets/194400/23144683/3725bab0-f7c1-11e6-8393-17e31ec60347.jpg)
![laughing](https://cloud.githubusercontent.com/assets/194400/23144686/3c268cec-f7c1-11e6-988a-8e56dde8d188.jpg)

**Comment by nelsonic** [comment]
![veranda-yoga](https://cloud.githubusercontent.com/assets/194400/23144699/4ba8d71a-f7c1-11e6-9673-446d6e8cdfb5.jpg)
![team-veranda](https://cloud.githubusercontent.com/assets/194400/23144703/545fb4aa-f7c1-11e6-9f24-a258bb5c0682.jpg)
good night everyone. ❤️ 
hope to see you all there `this` year! 👍

**Comment by jay-meister** [comment]
That trip was so much fun!

**Comment by iteles** [comment]
:laughing: Thanks Jack!

**Comment by nelsonic** [comment]
Here are a few more photos ... CC: @Cleop 
![elias-on-donut](https://user-images.githubusercontent.com/194400/27583900-e87e976c-5b2d-11e7-94fa-218869823809.jpg)
![team-on-flying-disk-petes-beach](https://user-images.githubusercontent.com/194400/27583917-f3d07b44-5b2d-11e7-9234-6b41bd762f43.jpg)
![team-on-flying-disk](https://user-images.githubusercontent.com/194400/27583922-f7f992d2-5b2d-11e7-8560-43eed312e8cc.jpg)
![sam-jack-playing-chess](https://user-images.githubusercontent.com/194400/27583924-fba921cc-5b2d-11e7-8e4d-a81f75198491.jpg)
![workin-hard](https://user-images.githubusercontent.com/194400/27583929-fe6fea1c-5b2d-11e7-8f09-3a0954b63a90.jpg)
![harry-and-ines-working](https://user-images.githubusercontent.com/194400/27583970-2f12eeee-5b2e-11e7-842e-9e57fc44dc1d.jpg)
![ines-showing-jack-and-marie-how-its-done](https://user-images.githubusercontent.com/194400/27583979-39995d26-5b2e-11e7-8c77-2b60564f8623.jpg)
![chillin-in-the-sun](https://user-images.githubusercontent.com/194400/27583932-00d7c1bc-5b2e-11e7-99b4-efdc0fa4a1ec.jpg)
![peeps-kayaking-far](https://user-images.githubusercontent.com/194400/27583948-15b2ed46-5b2e-11e7-8402-ca3e6940bf1b.jpg)
![peeps-kayaking](https://user-images.githubusercontent.com/194400/27583952-1935c4b6-5b2e-11e7-91a7-6c42da45e847.jpg)
![preparing-for-dunts](https://user-images.githubusercontent.com/194400/27583958-239c794a-5b2e-11e7-89b3-623f473d2dac.jpg)
![flying-on-donuts](https://user-images.githubusercontent.com/194400/27583959-26e80aec-5b2e-11e7-94bd-c2a40ad51953.jpg)
![naaz-drying-the-boat](https://user-images.githubusercontent.com/194400/27583961-29ea1fb4-5b2e-11e7-8749-5303ffe4c739.jpg)
![team-bouldering](https://user-images.githubusercontent.com/194400/27583989-404ddd9a-5b2e-11e7-875f-0ee50708ce33.jpg)
![team-bouldering-tight-space](https://user-images.githubusercontent.com/194400/27583994-44bcec36-5b2e-11e7-8012-ba5b4223ca30.jpg)
![team-boudlering-selfie-tight-space](https://user-images.githubusercontent.com/194400/27583999-485d3a9e-5b2e-11e7-8be5-0bb194a0b39e.jpg)
![harry-cliff-hanger](https://user-images.githubusercontent.com/194400/27584003-4d3221ec-5b2e-11e7-8a17-51a6340022dc.jpg)
![elias-on-a-rock](https://user-images.githubusercontent.com/194400/27584010-54391ad6-5b2e-11e7-8fe1-beb8c6fba67c.jpg)
![sam-marie-mountain-view](https://user-images.githubusercontent.com/194400/27584015-5b7fbe08-5b2e-11e7-914b-642b7652146e.jpg)
![eoin-jack-naaz-on-a-rock-with-a-view](https://user-images.githubusercontent.com/194400/27584024-62036874-5b2e-11e7-98f5-100baa4d6419.jpg)

**Comment by nelsonic** [comment]
And ...
![team-waterfall-bouldering](https://user-images.githubusercontent.com/194400/27584068-8ea740d0-5b2e-11e7-81c6-ece2c224f765.jpg)
![jack-resting-on-a-rock-pool](https://user-images.githubusercontent.com/194400/27584072-9095b7a0-5b2e-11e7-8120-dae5214ee9a2.jpg)
![sam-bouldering](https://user-images.githubusercontent.com/194400/27584082-99b538b0-5b2e-11e7-8f15-3769e5f2fb76.jpg)
![cristal-clear-water](https://user-images.githubusercontent.com/194400/27584084-9b683504-5b2e-11e7-85db-8da167f1304f.jpg)
![captain-elias](https://user-images.githubusercontent.com/194400/27584095-a2ed54da-5b2e-11e7-89b5-fa39a540da26.jpg)
![elias-playing-pool-bowling](https://user-images.githubusercontent.com/194400/27584102-a96281fa-5b2e-11e7-9275-35d162f5e6d2.jpg)
