### ISSUE TITLE
Key Safe?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/summer-2015#5]
To ensure people can get into the house without us having to be there to let them in, we could install a key safe: http://www.amazon.co.uk/Sentinel-Push-Button-wall-mounted/dp/B003J22WZ2
or: http://www.amazon.co.uk/Able2-PR60088-C500-Keysafe-Approved/dp/B0051BGKE8
see video: https://www.youtube.com/watch?v=L4rJ1_-VNV8

**Comment by iteles** [comment]
Turns out we don't need this for the summer specifically, though will be useful if we got for the airBNB option :+1:

**Comment by nelsonic** [comment]
For airBNB indeed... 
Want me to install one for your Brother before we leave for PT...? :wink:

**Comment by iteles** [comment]
Ha, no. I'll send him the link and he can install it himself! :stuck_out_tongue: 
Maybe when we come back in September though!

**Comment by nelsonic** [comment]
Heck, we could even _pay_ for it ourselves as a "_present_" to him, so you don't have to go there to open the flat for his guests anymore...! :confused:

**Comment by nelsonic** [comment]
re-open if required. 👍
