### ISSUE TITLE
dwylsummer 2017

### ISSUE THREAD

**Issue by iteles** [dwyl/summer-2015#51]
It's happening!

Proposed dates: 18/19th July to 2nd August 2017. 

More details to follow 😊

**Comment by iteles** [comment]
Confirmed this afternoon 👍

**Comment by ghost** [comment]
@iteles should we revise these dates then?

**Comment by iteles** [comment]
@markwilliamfirth Sorry, not sure what you mean! 
Do you mean revise as in revise the main readme to reflect these? If so, definitely!

**Comment by ghost** [comment]
I mean baring in mind the invitation for everyone to attend your event 😉  on the 5th august - should we revise the dwyl summer dates to encapsulate this date?

**Comment by ghost** [comment]
18th Jul - Aug 2nd

Will email out after Easter break

**Comment by nelsonic** [comment]
@iteles can you please share a link to the spreadsheet? (_thanks_!)

**Comment by iteles** [comment]
https://docs.google.com/spreadsheets/d/1k_B1sJtiXI8yexbgOrUgtPNXSJpwLbplXRRoCmM6um4/edit#gid=0

**Comment by nelsonic** [comment]
@iteles thanks. ❤️

**Comment by ghost** [comment]
@iteles I'm going to email everyone to remind them of this - is there any additional information besides the spreadsheet and dates that I should send?

**Comment by iteles** [comment]
Hmmmm... @markwilliamfirth Give me til lunch tomorrow to do a quick update on https://github.com/dwyl/summer/blob/master/useful-info.md ?

**Comment by ghost** [comment]
@iteles bump on this one! Have dates been revised?

**Comment by ghost** [comment]
🙌

**Comment by ghost** [comment]
Dates are 26th July - 6th August
