### ISSUE TITLE
Which Book(s) are You Taking with you to Porgual?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/summer-2015#52]
Next week, on our journey to Portugal, we _really_ don't have a lot of space to carry much. 😮 
I'm taking **2 books** with me:
+ Metaprogramming Elixir: https://www.amazon.co.uk/Metaprogramming-Elixir-Write-Less-Code/dp/1680500414
+ Time, Talent, Energy: https://www.amazon.co.uk/Time-Talent-Energy-Organizational-Productive/dp/1633691764

![image](https://user-images.githubusercontent.com/194400/27507114-7b7497c6-58c0-11e7-8a16-b56681c5fb8b.png)

The first one so I can "_get good_" at Elixir by practicing in the morning(s) `before` the day _officially_ starts  and the second is so that I have something "_relevant but light_" to read on the train or when waiting ... 

> Note: As a "backup" I have my Kindle but want to _avoid_ paying **_crazy_ Kindle prices** for books wherever possible...! >> _Audible_...?!

## Shipping Books to Portugal?

In _addition_ to these three, I was considering _shipping_ a couple more books to Portugal, because I _usually_ get through books quite quickly in the summer; specifically:
+ The Checklist Manifesto: https://www.amazon.co.uk/d/Books/Checklist-Manifesto-How-Things-Right-Atul-Gawande/1846683149
+ Being Mortal: https://www.amazon.co.uk/Being-Mortal-Illness-Medicine-Wellcome/dp/1846685826

We have over a hundred books in the Palmer's Road Flat ... 
and I'd like to start boxing them up _today_.
Please chose the book(s) you want to read next week 
and any others you are going to Ship to Portugal.

**Comment by samhstn** [comment]
Great, looking forward to reading https://www.amazon.co.uk/Metaprogramming-Elixir-Write-Less-Code/dp/1680500414 in Portugal, thanks @nelsonic

**Comment by nelsonic** [comment]
Totes want to _Listen_ to this book on Audible next: 
https://www.amazon.co.uk/Becoming-Brilliant-Successful-Children-Lifetools/dp/1433822393

**Comment by iteles** [comment]
I took three books and didn't finish any of them 😳 
+ [Mindset](https://www.amazon.co.uk/Mindset-Updated-Changing-Fulfil-Potential/dp/147213995X) by Carol Dweck
  + I got about a third of the way through this and found the information useful but unendingly repetitive as it cycled through the different areas of life where it could be used
  + I switched to the audiobook instead and am 1 chapter away from the end 🎉 
+ [Tools of Titans](https://www.amazon.co.uk/Tools-Titans-Billionaires-World-Class-Performers-ebook/dp/B01LF32ZNU/) by Tim Ferriss (thanks @nelsonic for carrying this tome)
  + This is more of a 'dip in and out' book and I wasn't expecting to finish it; I still need to figure out how best to catalogue the information in this book in a way that I can utilise it
+ [Talk like TED](https://www.amazon.co.uk/Talk-Like-TED-Speaking-Secrets/dp/1509867392/) by Carmine Gallo
  + Didn't even make a start on this one 😬  

I also only made it about a third of way through the `Programming Elixir` book :(
Hoping to change that in the next month: https://github.com/iteles/personal-goals/issues/5

**Comment by iteles** [comment]
@nelsonic I'm closing this issue as the question is answered, but we need a better way to track books we have read & want in the dwyl library!
