### ISSUE TITLE
dwyl summer 2018 dates

### ISSUE THREAD

**Issue by Cleop** [dwyl/summer-2015#55]
@nelsonic says Mid July may be the time for dwyl summer 2018 but is not yet confirmed.

More details to be added here!

🎉 😄 ❤️ 🌺 🌞

**Comment by iteles** [comment]
We'll email the house owners today and get the ball rolling!

**Comment by iteles** [comment]
Looking like late June/ early July at the moment, definitely not August.

**Comment by Cleop** [comment]
@iteles - any update on this one? Want to get some flights booked around late June and have a wedding mid July, so any more info would be much appreciated! Wouldn't want to miss out on this!!! ❤️

**Comment by iteles** [comment]
I have been promised an update _this_ week, there are apparently 3 more people to weigh in on this (and my mother lost her voice over the weekend so her corralling of all required parties has been somewhat hampered by this 😬)

**Comment by Cleop** [comment]
Great to know, thanks @iteles 😊  Hope you've prescribed her lots of honey, lemon and ginger tea! 🍵

**Comment by iteles** [comment]
So far it's looking like wither 16th - 29th July or 23rd July - 5th August, but more confirmation coming!

**Comment by iteles** [comment]
Latest: 23rd July - 5th August (except not the 5th August coz... anniversary 👰🤵) OR in the late September/October timeframe! 

Most likely between the lakehouse & Braga.

**Comment by nelsonic** [comment]
CC: @shouston3 & @Danwhy 
(_summer dates TBC..._)

**Comment by Cleop** [comment]
❤️ July/August if it's warmer 🌞= ✅   🌥= ❌

**Comment by iteles** [comment]
Spreadsheet is _up_ 💥 ! 
We've gone for mid-week to mid-week so the flights are cheaper but accommodation is available if people arrive early and until 2nd August 🎉 

**Please fill this in!**
https://docs.google.com/spreadsheets/d/15KfutKnJ_I_awgV6DiIRZDIln1WP93jlqbJFtL5VDG0/edit#gid=0

**Comment by iteles** [comment]
@Conorc1000 @roryc89 and @naazy have noted that they won't be able to make it this year as they already have prior commitments 😭 We need to get these in the calendar earlier!

**Comment by Cleop** [comment]
@Conorc1000 @roryc89 - Who will be masters of the BBQ now? @naazy - who am I going to cook with?! 😢

**Comment by nelsonic** [comment]
Stoked everyone was able to join us in 2018. 🎉 
2019 is going to be on a _whole_ other level! ❤️
