### ISSUE TITLE
dwyl summer 2019 dates

### ISSUE THREAD

**Issue by Cleop** [dwyl/summer-2015#56]
@iteles @nelsonic - do we have a rough idea of dates for dwyl summer 2019?

I'm looking at getting involved with some hobbies that have requested to know my weekend availability and I wanted to factor in time for dwyl summer ❤️

**Comment by nelsonic** [comment]
@Cleop as you may be aware, we are planning to do something _very_ different for ❤️✅☀️🏊‍♀️5️⃣ 
Both the _number_ of people and the duration will be expanded _considerably_ from previous years. 
We don't expect _anyone_ to be in Portugal for the _whole_ summer although you are most _welcome_ to!
At this stage your best bet is to organise your hobbies for the most _convenient_ weeks/weekends and come to Portugal whenever you _can_. More info to follow when we have [@home](https://github.com/dwyl/home) open. 🏡⏳

**Comment by iteles** [comment]
Will reopen for 2020 if travel is allowed by then!
