### ISSUE TITLE
Pitch

### ISSUE THREAD

**Issue by nelsonic** [dwyl/summer-2015#6]
So... in the interest of lighting a fire under us, I've signed us up to pitch **Summer 2015** to FAC5 on Monday 7th June ... :open_mouth:

**Comment by iteles** [comment]
Of course you have. Because we don't have enough to sort out before [Tuesday's LadiesWhoCode meetup](http://www.meetup.com/Ladies-Who-Code-UK/events/222452944/).
Interesting you managed to do that in the first place given that Mondays are supposed to be role presentation days, not MVP days.

**Comment by nelsonic** [comment]
Wednesday would have been better, _agreed_. Except that it would have to be a Lunch Time Pitch because I'm flying out before the "_usual_" (after work) pitch time...

**Comment by iteles** [comment]
I'm going to the market :arrow_right: lunch :arrow_right: start planning.

**Comment by iteles** [comment]
I think this was covered by the writing of the [readme](https://github.com/dwyl/summer-2015/blob/6a1c8b56db02ddd8b106ebeb6d1b5911dadd1cd2/README.md) in the `summer-2015` repo.

It will need to be revisited when the summer ends as part of 'what we learned and why 2016 will be the most exciting thing to ever happen in the history of anything', but we should open a separate issue for that as this was specifically about the FAC5 pitch.

Do you think we can close this now @nelsonic ?

**Comment by nelsonic** [comment]
Yes. next time we'll have photos to do all the "talking" for us. :wink:
