### ISSUE TITLE
UK extension lead so people don't have to bring adapters

### ISSUE THREAD

**Issue by nelsonic** [dwyl/summer-2015#7]
should we take a couple of extension leads so people don't have to buy/take UK>EU for all their devices?

**Comment by iteles** [comment]
Makes sense as long as you don't think it'll overload the adapter (don't see why it should). I'll add it to the list.

**Comment by nelsonic** [comment]
Should I take one on Wednesday...?

**Comment by iteles** [comment]
If you have space. There are PLENTY of other things on the list that need to go to Portugal so you know, take your pick :stuck_out_tongue:

**Comment by nelsonic** [comment]
@iteles where is this "_List_" (_of things to take to PT_) that you speak of?

Thinking of getting one of these: http://www.amazon.co.uk/Sivitec-Switched-Extension-Protection-Indicator/dp/B00KWMX2YM (or do you think we should get [**_two**_](https://youtu.be/0dMofPfpJsE?t=7s) extensions...?

**Comment by iteles** [comment]
I think one is perfect, then we'll take the six plug extension we already have. 

I have a list on my phone I've been adding to since March but we should probably have a public one that includes books etc!

**Comment by iteles** [comment]
Bought. Done.
