### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by nelsonic** [dwyl/summer-2015#8]
We need a great code of conduct everyone needs to read and agree to _before_ we launch this summer!

A few simple rules e.g:
- Avoid making Loud Noise/Music (_in general but especially_) between  **hh:mm PM** and **hh:mm AM** #**QuietCreativity**
- Leave areas how you would expect to find them (_tidy_) #**GoldenRule**
- Behave as you would if your mother (or other most respected person) was watching 

etc...

@iteles you have done more research into this than anyone else. could you please collate your findings into an **MD** file (_preferably its own repo so others can re-use it_) **_Thanks**_! :+1:

**Comment by iteles** [comment]
I started with one a little specific to the summer and will generalise into a dwyl code of conduct for sure!

**Comment by iteles** [comment]
[Dan Ariely](http://danariely.com/) has done some fascinating research into the field of (_dis_)honesty and cheating which I've been reading about recently.    

He does one particular set of experiments (the matrix experiments) where there is always a small _average_ level of cheating (what the participants deem as the **socially accepted** level). _However,_ when the student were asked to [sign their college's honor code](http://chqdaily.com/2012/08/06/ariely-small-scale-cheating-allows-us-to-still-feel-good-about-ourselves/) [search for 'honor code' in the article] _despite_ the fact that these college _didn't actually have_ honour codes, **cheating was completely eradicated**. It seems that signing the code is a simple reminder of what is _right_ and therefore they don't cheat.
_(Aside: for me, one of the most interesting parts of these experiments is that the Princeton students who not only **have** an honour code but ~~spend~~ also get a **full week of induction on morality and ethics** cheat just as much as other college students in the experiments when **neither** group is made to sign the honour code)_

**The relevance to this issue** is this: I wonder whether asking people to **good naturedly  _sign_ a code of conduct** would make _any_ difference to their behaviour from then onwards. 

My _hypothesis_ is that any changes would be short-lived (probably 24 hours at most) but it's a fascinating field of study!

**Comment by nelsonic** [comment]
That _is **fascinating**_ but _**not unexpected**_. 
The point of this issue is to create a _General **Code of Conduct**_ to be placed in: https://github.com/dwyl/start-here for _**everyone**_ to read and _**Optionally** sign_.

Most people will _**naturally**_ observe the "_**Golden Rule**_" but for those who don't
(_the usual suspects who are super loud/inconsiderate and leave FAC in a mess when they go home for the day_) it would be _interesting_ to see if _those_ individuals decide _not_ to sign the Code ...
That would be an (_indirect though clear_) acknowledgement that their behaviour is not conducive to working in a group/team ...

The other hypothesis is: (given that **dwyl** will be a _social_ app) if everyone was able to _see_ on your **dwyl** profile if you had signed "The DWYL Code" (_or chosen to skip  it_) would that make you a less attractive team mate for activities? 

Would we see people _retrospectively_ going back, reading The Code and signing it?

**Comment by nelsonic** [comment]
@iteles there's a site for this: http://todogroup.org/opencodeofconduct/
But (_I still think_) we need our own repo...

**Comment by iteles** [comment]
Totally agree: https://github.com/dwyl/code-of-conduct/blob/16813b5262ac22d020a593d50070c2aa7f8a85af/why-we-wrote-this.md

**Comment by nelsonic** [comment]
Does that mean we can **_close**_ this issue?

**Comment by iteles** [comment]
I reckon so, any issues/improvements on the code of conduct should be opened against the [code of conduct repo](https://github.com/dwyl/code-of-conduct). :+1:

**Comment by iteles** [comment]
Also... this one https://github.com/dwyl/start-here/issues/20
