### ISSUE TITLE
Wanna Try Light Painting?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/summer-2015#9]
![light painting](https://c2.staticflickr.com/4/3478/5813641070_1c58765e05_b.jpg)

@iteles what do we need to take with us from Ldn to be able to do a bit of light painting...?

**Comment by iteles** [comment]
Couple of tripods and a good camera (one that allows you 10 seconds + of exposure) and then just torches/sparklers/lighters/anything that emits light.

The question is one camera or two? :wink:

**Comment by nelsonic** [comment]
![two daddies](http://itsconceivablenow.com/wp-content/uploads/2011/12/stories_jerry.jpg)

**Comment by iteles** [comment]
One camera then 'coz I ain't no Mary Poppins yo.

**Comment by iteles** [comment]
After some interesting attempts, we actually did quite well! Thanks everyone (@benjaminlees, @msmichellegar, Benji's girlfriend Naomi and I managed that relatively successful 'dwyl' at the end :tada:)

![img_5279](https://cloud.githubusercontent.com/assets/4185328/9717533/77b720c2-556b-11e5-9ffc-7592c59f57e2.jpg)
![img_5285](https://cloud.githubusercontent.com/assets/4185328/9717535/77b93c90-556b-11e5-9327-9f0ecd741be9.jpg)
![img_5286](https://cloud.githubusercontent.com/assets/4185328/9717536/77b9b396-556b-11e5-9509-cc50e1ad0627.jpg)
![img_5282](https://cloud.githubusercontent.com/assets/4185328/9717534/77b8f8d4-556b-11e5-8e3f-ead8b35f520e.jpg)
![img_5289](https://cloud.githubusercontent.com/assets/4185328/9717537/77ba0166-556b-11e5-8d5a-97cc3a9a50a3.jpg)
